# Generated by Django 5.1.7 on 2025-03-15 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='branch',
            field=models.CharField(choices=[('CS', 'Computer science'), ('AMC', 'Applied Matghematics and Computing'), ('ENS', 'Environment Science')], default='Unknown', max_length=50),
        ),
    ]
